spring.application.name=demo
spring.datasource.url=jdbc:sqlite:sklinaw.db
server.port=8085
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update