spring.application.name=demo
spring.datasource.url=jdbc:sqlite:${project.basedir}/sklinaw.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=SKLinaw
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot